### ISSUE TITLE
Shell script executed but no output

### ISSUE THREAD

**Issue by kekko1212** [fballiano/magento-full-catalog-translate#12]
Hi Francesco, when I launch the shell script, it is executed without any information about failure (not even with the debug flag).

Do you think that bundled products are supported by your extension?

**Comment by fballiano** [comment]
there should not be any problem with bundled products, did you set the "fb_translate" attribute only for the correct store view?

**Comment by alexander-sibert** [comment]
I have the same issue in Magento 1.9.2.3:

For example: Source StoreView "de" (German) translate to StoreView "it" (Italian) with Google Translate. I set the Attribute Translate one product in StoreView "it" to "yes". 

<img width="897" alt="bildschirmfoto 2016-01-23 um 13 41 27" src="https://cloud.githubusercontent.com/assets/264523/12530208/0980daf2-c1d7-11e5-8940-62b6697fd2d2.png">

Executed in SSH with php_cli fballiano_full_catalog_translate.php de it and tried also debug function but i  don't see nothing and nothing is translated. I did put in configuration the Google Translate API Key.

<img width="524" alt="bildschirmfoto 2016-01-23 um 13 38 44" src="https://cloud.githubusercontent.com/assets/264523/12530195/aa84a254-c1d6-11e5-93eb-417fc93d1897.png">

**Comment by fballiano** [comment]
I will try to test it on a newer magento as soon as possible

**Comment by alexander-sibert** [comment]
Maybe i do anything wrong but i have no outputs in the logs.

**Comment by fballiano** [comment]
auch! i think i found the most stupid bug ever and i can't believe it ended up commited.
just give me a few min

**Comment by fballiano** [comment]
should be solved by 0.7.1.
really sorry for that.
let me know

**Comment by alexander-sibert** [comment]
Thanks i will update it ;)
