### ISSUE TITLE
Running through php / bash script

### ISSUE THREAD

**Issue by natedesigns** [fballiano/magento-full-catalog-translate#16]
When running this like:

shell_exec('php fballiano_full_catalog_translate.php default 12');

It is returning:
`Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /lib/Zend/Db/Adapter/Pdo/Abstract.php:129`

If I run the same code into the command line, it works a dream `php fballiano_full_catalog_translate.php default 12`.

I have tried coding this as both a php script and bash, alas same error. I've found that if I take the ` extends Mage_Shell_Abstract` from your core file, then the code executes without error. So it's to do with the integration with abstract.ph as per error. 

What I'm trying to achieve is running this script file on a cron job to translate new products we have added to our store on a daily basis. 

I hope I'm not being naive, as I've tried a number of things to try and resolve. Sorry to post this as an issue, as it's not. Thanks in advance.

**Comment by fballiano** [comment]
maybe when you call the "php" executable from the other script, the environment is different thus it doesn't work (some env variables missing, different php version... which is a classic in multiwebsite hostings).

**Comment by fballiano** [comment]
closed because of no feedback
