### ISSUE TITLE
Terminated

### ISSUE THREAD

**Issue by boonzik** [fballiano/magento-full-catalog-translate#18]
Ciao,
abbiamo seguito le indicazioni ma quando lanciamo il comando da shell riceviamo "Terminated" ma i campi selezionati in backend non vengono tradotti. Hai qualche indicazione a riguardo???

Grazie mille

**Comment by fballiano** [comment]
come lanciate lo script di shell?

**Comment by boonzik** [comment]
Grazie della risposta immediata.

php fballiano_full_catalog_translate.php it en 

dove en è il codice della vista da tradurre e it il codice della vista da dove importare i testi.

**Comment by fballiano** [comment]
se non stampa nemmeno la riga:

Translating {$row["sku"]} from {$this->language_source} to {$this->language_dest}... 

è perché non sta trovando alcun prodotto da tradurre, li avete marcati come da tradurre, salvando però l'attributo nella store view di destinazione?

provate a debuggare la riga 95 dello script, che esegue questa query:
        $products = Mage::getSingleton("core/resource")->getConnection("core_read")->fetchCol("SELECT entity_id FROM {$table_name} WHERE attribute_id={$attribute_id} AND store_id={$store_id_dest} AND value=1");

dovrebbe stare li l'inghippo

**Comment by boonzik** [comment]
Grazie mille, abbiamo risolto. Gentilissimo e complimenti per il plugin.

A presto.
