### ISSUE TITLE
All descriptions empty?

### ISSUE THREAD

**Issue by gewerbetrend** [fballiano/magento-full-catalog-translate#5]
Hello again ;-)

I used the shell command now.. but after the script was done I saw that all descriptions in the target store are empty... 
I translated from german to spain... 

Google API is correct.. settings looks also ok.. whats wrong?

Thanks and regards
Andy

**Comment by fballiano** [comment]
you should get a much more detailed debug with 0.6.0, can you try to download it and enable "debug" and "dry" options at command line? how to is directly written in the help of the shell script itself.
