### ISSUE TITLE
Error when ran

### ISSUE THREAD

**Issue by DavidMaran** [fballiano/magento-full-catalog-translate#8]
Everything seems fine until when i run it. 
Command being ran: php fballiano_full_catalog_translate.php en fr

Then i get the following error: 
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AND store_id=4 AND value=1' at line 1' in /home/ibottles/public_html/lib/Zend/Db/Statement/Pdo.php:228
Stack trace:
#0 /home/ibottles/public_html/lib/Zend/Db/Statement/Pdo.php(228): PDOStatement->execute(Array)
#1 /home/ibottles/public_html/lib/Varien/Db/Statement/Pdo/Mysql.php(110): Zend_Db_Statement_Pdo->_execute(Array)
#2 /home/ibottles/public_html/app/code/core/Zend/Db/Statement.php(291): Varien_Db_Statement_Pdo_Mysql->_execute(Array)
#3 /home/ibottles/public_html/lib/Zend/Db/Adapter/Abstract.php(479): Zend_Db_Statement->execute(Array)
#4 /home/ibottles/public_html/lib/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT entity_i...', Array)
#5 /home/ibottles/public_html/lib/Varien/Db/Adapter/Pdo/Mysql.php(428): Zend_Db_Adapter_Pdo_Abstract->que in /home/ibottles/public_html/lib/Zend/Db/Statement/Pdo.php on line 234

Any way you can help with this problem?

**Comment by fballiano** [comment]
do you have 2 store views with "en" and "fr" store code right?

**Comment by DavidMaran** [comment]
Yes Correct.

**Comment by fballiano** [comment]
can you try the previous version to find out if it's something related to the categories translation?
it seems you don't have the "fb_translate" attribute for products or categories

**Comment by DavidMaran** [comment]
Hi That seems still not to work, now i get the message 'Terminated' 

root@921991 [/home/*****/public_html/shell]# php fballiano_full_catalog_translate.php en de
Terminated

**Comment by fballiano** [comment]
could you please try 0.7.1?

**Comment by fballiano** [comment]
closing for no feedback
